
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - kubeflow.org
  resources:
    - pytorchjobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - kubeflow.org
  resources:
    - pytorchjobs/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - xdl.alibaba.com
  resources:
    - xdljobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - xdl.alibaba.com
  resources:
    - xdljobs/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - xgboostjob.kubeflow.org
  resources:
    - xgboostjobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - xgboostjob.kubeflow.org
  resources:
    - xgboostjobs/status
  verbs:
    - get
    - patch
    - update