
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - elasticdljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - elasticdljobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - training.kubedl.io
  resources:
  - marsjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - marsjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - training.kubedl.io
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - mpijobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - training.kubedl.io
  resources:
  - pytorchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - pytorchjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - training.kubedl.io
  resources:
  - tfjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - tfjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - training.kubedl.io
  resources:
  - xdljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - xdljobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - training.kubedl.io
  resources:
  - xgboostjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.kubedl.io
  resources:
  - xgboostjobs/status
  verbs:
  - get
  - patch
  - update
